<a href="https://colab.research.google.com/github/Kuroy22/MAT422/blob/main/1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 1.2 Takeaways:
Gram-Schmidt Process
Eigenvalues and Eigenvectors

Gram-Schmidt Process

In [46]:
import matplotlib.pyplot as plt
import numpy as np

#random matrix which will be used for Gram Schmidt and Eignenvalues/Eignenvectors
A=np.random.rand(3,3)*100
print(A)

[[27.46630817 32.02345694 49.94090826]
 [39.73545908 97.58648098 14.6307699 ]
 [ 8.68889671 97.03335476 93.94090208]]
[[99.06020124 14.86633999 12.37768885]
 [35.19001397 42.72462177 84.66279746]
 [23.89310862 77.81261753 53.88717756]]


Function to perform Gram Schmidt

In [45]:

#Gram Schmidt
def gs(A):


  temp= np.copy(A)

  Final = np.zeros(A.shape)
  Final[:,0]= A[:,0] /np.linalg.norm(A[:,0])

  for i in range(1, temp.shape[1]):
    temp2=A[:,i]

    for j in range(i):
        temp2 -= np.multiply((np.dot(temp[:,j], A[:,i]) / np.dot(temp[:,j], temp[:,j])),temp[:,j])
    temp[:,i]=temp2
    Final[:,i]=temp[:,i]/ np.linalg.norm(temp[:,i])
  return Final
print("Gram-Schmidt of A")
print(gs(A))


Gram-Schmidt of A
[[ 0.65311428 -0.74016311  0.160001  ]
 [ 0.48732452  0.57253849  0.65932882]
 [ 0.5796176   0.35264466 -0.73463269]]


Eignvalues and Eigenvectors


numpy has  a built in function to calculate Eignvalues and Eignevectors

In [49]:
from numpy.linalg import eig
val, vec = eig(A)
print('Eigenvalue: ',val)
print('Eigenvector: ',vec)
#values with 0j are to indicate that it is a complex value

Eigenvalue:  [157.07499594 +0.j         30.95934765+24.8491714j
  30.95934765-24.8491714j]
Eigenvector:  [[-0.41607155+0.j          0.6808178 +0.j          0.6808178 -0.j        ]
 [-0.4694513 +0.j         -0.3762623 -0.24990721j -0.3762623 +0.24990721j]
 [-0.77878107+0.j          0.28888828+0.49900276j  0.28888828-0.49900276j]]
